modLoader="javafml"
loaderVersion="${loader_version}"
license="LGPL-3.0-or-later"
issueTrackerURL="https://github.com/TheIllusiveC4/CherishedWorlds/issues"
logoFile="cherishedworlds_icon.png"
logoBlur=false
[[mods]]
modId="cherishedworlds"
version="${version}"
displayName="Cherished Worlds"
displayURL="https://github.com/TheIllusiveC4/CherishedWorlds"
authors="C4"
description='''
Favorite/pin/bookmark certain worlds, which will always be at the top of the list and cannot be deleted.
'''
[[dependencies.cherishedworlds]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version}"
    ordering="NONE"
    side="CLIENT"
[[dependencies.cherishedworlds]]
    modId="minecraft"
    mandatory=true
    versionRange="${mc_version}"
    ordering="NONE"
    side="CLIENT"
